export const courses = [
  "B.A Professional French",
  "BSc. Nursing",
  "BSc. Chemistry",
  "BSc. Agribusiness",
  "BSc. Wildfire and Range Management",
  "BSc. Agriculture",
  "BSc. Biological Science",
  "BSc. Medical Biodiagnostic Science",
  "BSc. Computer Science",
  "BSc. Information Technology",
  "BSc. Actuarial Science",
  "BSc. Resource Enterprise and Entrepreneurship",
  "BSc. Mathematics",
  "BSc. Agricultural Engineering",
  "BSc. Planning and Sustainability",
  "BSc. climate Change and Sustainable Development",
  "BSc. Computer Engineering",
  "BSc. Electrical and Electronic Engineering",
  "BSc. Mechanical Engineering",
  "BSc. Environmental Engineering",
  "BSc. Renewable Energy Engineering",
  "BSc. Petroleum Engineering",
  "BSc. Civil Engineering",
  "BSc. Statistics",
  "BSc. Fire and Disaster Management",
  "BSc. Hospitality Management",
  "BSc. Natural Resource",
  "Diploma in Information Technology",
  "Diploma in Computer Science",
  "Diploma in Enterprise Management",
  "Diploma in Hospitality Management",
  "Diploma in Insurance",
  "Diploma in Natural Resources Management",
  "Diploma in Fire, Safety and Disaster Management",
  "Diploma in Electrical and Electronic Engineering",
  "Diploma in Geo-Information Science",
  "Diploma in Agriculture",
  "Diploma in Statistics",
  "MBA/MPhil Agribusiness Management",
  "MSc./MPhil Climate Change",
  "MSc./MPhil/PhD Crop Sciences",
  "MSc./MPhil Environment Planning and Sustainability",
  "MSc./PhD Sustainable Energy Management",
  "MSc./MPhil/PhD in Computer Science",
  "MSc./PhD Environmental Engineering Management",
  "MPhil Applied Mathematics",
  'MPhil/PhD Social Forestry and Environmental Governance',
];


